# This is a basic workflow to help you get started with Actions

name: Katalon

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Katalon
        run: |
          cmd /c "C:\Users\503422996\Downloads\Katalon_Studio_Engine_Windows_64-10.2.0\katalonc.exe" -noSplash -runMode=console -projectPath="C:\Users\503422996\Katalon Studio\Demo_24th\Demo_24th.prj" -retry=0 -testSuitePath="Test Suites/DemoSuite" -executionProfile="default" -browserType="Chrome" -apiKey=${{ secrets.KT_APIKEY }}""
          
